ALTER TABLE sport_center.bookings ADD COLUMN IF NOT EXISTS down_payment NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sport_center.bookings ADD COLUMN IF NOT EXISTS is_dp_paid BOOLEAN NOT NULL DEFAULT FALSE;
