import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import facilitiesRouter from "./facilities";
import availabilityRouter from "./availability";
import bookingsRouter from "./bookings";
import paymentsRouter from "./payments";
import promosRouter from "./promos";
import schedulesRouter from "./schedules";
import customersRouter from "./customers";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import configRouter from "./config";
import storageRouter from "./storage";
import membershipsRouter from "./memberships";
import discountSettingsRouter from "./discountSettings";
import apMembersRouter from "./apMembers";
import cancellationsRouter from "./cancellations";
import rescheduleRouter from "./reschedule";
import bookingExtensionsRouter from "./bookingExtensions";
import auditLogsRouter from "./auditLogs";
import pricingRulesRouter from "./pricingRules";
import maintenanceRouter from "./maintenance";
import reviewsRouter from "./reviews";
import calendarRouter from "./calendar";
import reportsRouter from "./reports";
import notificationTemplatesRouter from "./notificationTemplates";
import bookingHistoryRouter from "./bookingHistory";
import qrCheckinRouter from "./qrCheckin";
import tenantsRouter from "./tenants";
import syncRouter from "./sync";
import whatsappRouter from "./whatsapp";
import authSocialRouter from "./auth-social";
import verificationLogsRouter from "./verificationLogs";
import companyInvoicesRouter from "./companyInvoices";
import companyVerificationsRouter from "./companyVerifications";
import companyBillingRequirementsRouter from "./companyBillingRequirements";

import taxConfigRouter from "./taxConfig";
import taxReportRouter from "./taxReport";
import sportCenterBookingsRouter from "./sportCenterBookings";
import operatorAccountsRouter from "./operatorAccounts";
import companyBookingsRouter from "./companyBookings";
import customerSheetsRouter from "./customerSheets";
import bankReconciliationRouter from "./bankReconciliation";
import bankReconciliationSheetsRouter from "./bankReconciliationSheets";
import bookingGroupsRouter from "./bookingGroups";
import waBookingsAdminRouter from "./waBookingsAdmin";
import waAiAdminRouter from "./waAiAdmin";
import seedDemoRouter from "./seedDemo";
import systemAdminRouter from "./systemAdmin";
import expensesRouter from "./expenses";
import documentTemplatesRouter from "./documentTemplates";
import invoicesRouter from "./invoices";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(configRouter);
router.use(authRouter);
router.use(authSocialRouter);
router.use(facilitiesRouter);
router.use(availabilityRouter);
router.use(bookingGroupsRouter);
router.use(bookingsRouter);
router.use(paymentsRouter);
router.use(promosRouter);
router.use(schedulesRouter);
router.use(customersRouter);
router.use(dashboardRouter);
router.use(settingsRouter);
router.use(membershipsRouter);
router.use(discountSettingsRouter);
router.use(apMembersRouter);
router.use(cancellationsRouter);
router.use(rescheduleRouter);
router.use(bookingExtensionsRouter);
router.use(auditLogsRouter);
router.use(pricingRulesRouter);
router.use(maintenanceRouter);
router.use(reviewsRouter);
router.use(calendarRouter);
router.use(reportsRouter);
router.use(notificationTemplatesRouter);
router.use(bookingHistoryRouter);
router.use(qrCheckinRouter);
router.use(tenantsRouter);
router.use(syncRouter);
router.use(whatsappRouter);
router.use(verificationLogsRouter);
router.use(companyInvoicesRouter);
router.use(companyVerificationsRouter);
router.use(companyBillingRequirementsRouter);
router.use(taxConfigRouter);
router.use(taxReportRouter);
router.use(sportCenterBookingsRouter);
router.use(operatorAccountsRouter);
router.use(companyBookingsRouter);
router.use(customerSheetsRouter);
router.use(bankReconciliationRouter);
router.use(bankReconciliationSheetsRouter);
router.use(waBookingsAdminRouter);
router.use(waAiAdminRouter);
router.use(seedDemoRouter);
router.use(systemAdminRouter);
router.use(expensesRouter);
router.use(documentTemplatesRouter);
router.use(invoicesRouter);

export default router;
